# Generated by Django 4.2.7 on 2023-12-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auto_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
