# Generated by Django 4.2.7 on 2024-01-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_item_auto_add_cartmodel_added_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_upload',
            field=models.FileField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
