# Generated by Django 4.2.7 on 2024-01-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_img_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='added_item_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
    ]
